import raw from "./manifest.json";

export type FieldType = "text" | "textarea" | "checkbox" | "canvas";

export type ManifestField = {
  id: string;
  page: number;
  day: number | null;
  type: FieldType;
  label: string | null;
  section: string | null;
};

export type Manifest = {
  version: string;
  fields: ManifestField[];
};

// `manifest.json` is regenerated by `workbook/src/build_web.py` (which also
// copies it here) — see workbook/README.md. Do not hand-edit.
export const manifest = raw as Manifest;

const byId = new Map<string, ManifestField>(manifest.fields.map((f) => [f.id, f]));

export function getField(fieldId: string): ManifestField | undefined {
  return byId.get(fieldId);
}

export function fieldExists(fieldId: string): boolean {
  return byId.has(fieldId);
}

/** Distinct course day numbers that have at least one field (excludes generic/null-day pages). */
export const courseDays: number[] = Array.from(
  new Set(manifest.fields.map((f) => f.day).filter((d): d is number => d !== null))
).sort((a, b) => a - b);

/** Total field count per course day — the denominator for "% filled" progress. */
export const fieldsPerDay: Record<number, number> = manifest.fields.reduce(
  (acc, f) => {
    if (f.day !== null) acc[f.day] = (acc[f.day] ?? 0) + 1;
    return acc;
  },
  {} as Record<number, number>
);
